server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://39.96.59.235/wx_1901
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Xiaoluo301817.
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  activemq:
    broker-url: http://39.96.59.235:61616/
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100

mybatis:
  config-location: classpath:config/mybatis-cfg.xml
  mapper-locations: classpath:config/mapper/**.xml


immoc:
  security:
    browser:
      loginPage: /index.html


